# Generated by Django 5.0 on 2023-12-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minamax', '0002_remove_bet_choice_text_bet_putting_event_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='number',
        ),
        migrations.AlterField(
            model_name='bet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='possibility',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
